import type { NodeTypeDefinition } from '../types/graph';

export const BUILTIN_NODE_TYPES: Record<string, NodeTypeDefinition> = {
  // Product & High Level
  project: {
    type: 'project',
    label: 'Project',
    category: 'product',
    description: 'High-level project or system umbrella',
    icon: 'FolderGit2',
    color: '#09090b',
    badgeBg: '#f4f4f5',
    borderColor: '#27272a',
  },
  product: {
    type: 'product',
    label: 'Product',
    category: 'product',
    description: 'User-facing product offering or application',
    icon: 'Box',
    color: '#18181b',
    badgeBg: '#f4f4f5',
    borderColor: '#3f3f46',
  },
  feature: {
    type: 'feature',
    label: 'Feature',
    category: 'product',
    description: 'Functional capability delivering user value',
    icon: 'Sparkles',
    color: '#27272a',
    badgeBg: '#f4f4f5',
    borderColor: '#52525b',
  },
  requirement: {
    type: 'requirement',
    label: 'Requirement',
    category: 'product',
    description: 'System or product requirement specification',
    icon: 'CheckSquare',
    color: '#3f3f46',
    badgeBg: '#f4f4f5',
    borderColor: '#71717a',
  },

  // Architecture & Backend
  module: {
    type: 'module',
    label: 'Module',
    category: 'architecture',
    description: 'Logical grouping of related functionality',
    icon: 'Layers',
    color: '#18181b',
    badgeBg: '#f4f4f5',
    borderColor: '#3f3f46',
  },
  service: {
    type: 'service',
    label: 'Service',
    category: 'architecture',
    description: 'Autonomous backend service or microservice',
    icon: 'Cpu',
    color: '#09090b',
    badgeBg: '#f4f4f5',
    borderColor: '#27272a',
  },
  api: {
    type: 'api',
    label: 'API',
    category: 'architecture',
    description: 'Application Programming Interface gateway or spec',
    icon: 'Network',
    color: '#27272a',
    badgeBg: '#f4f4f5',
    borderColor: '#52525b',
  },
  endpoint: {
    type: 'endpoint',
    label: 'Endpoint',
    category: 'architecture',
    description: 'Specific HTTP/gRPC/WebSocket endpoint',
    icon: 'Radio',
    color: '#3f3f46',
    badgeBg: '#f4f4f5',
    borderColor: '#71717a',
  },
  event: {
    type: 'event',
    label: 'Event / Message',
    category: 'architecture',
    description: 'Asynchronous event, webhook, or message topic',
    icon: 'Zap',
    color: '#18181b',
    badgeBg: '#f4f4f5',
    borderColor: '#3f3f46',
  },
  integration: {
    type: 'integration',
    label: 'Integration',
    category: 'architecture',
    description: 'Third-party integration or external service connector',
    icon: 'Cable',
    color: '#27272a',
    badgeBg: '#f4f4f5',
    borderColor: '#52525b',
  },

  // UI & Frontend
  page: {
    type: 'page',
    label: 'Page / Screen',
    category: 'product',
    description: 'Application view, screen, or route',
    icon: 'Layout',
    color: '#09090b',
    badgeBg: '#f4f4f5',
    borderColor: '#27272a',
  },
  component: {
    type: 'component',
    label: 'UI Component',
    category: 'code',
    description: 'Reusable visual interface building block',
    icon: 'Component',
    color: '#27272a',
    badgeBg: '#f4f4f5',
    borderColor: '#52525b',
  },
  'ui-element': {
    type: 'ui-element',
    label: 'UI Element',
    category: 'code',
    description: 'Atomic visual widget, button, or input field',
    icon: 'MousePointer',
    color: '#52525b',
    badgeBg: '#f4f4f5',
    borderColor: '#a1a1aa',
  },

  // Code & Implementation
  function: {
    type: 'function',
    label: 'Function / Method',
    category: 'code',
    description: 'Discrete executable function or algorithm',
    icon: 'Code2',
    color: '#18181b',
    badgeBg: '#f4f4f5',
    borderColor: '#3f3f46',
  },
  file: {
    type: 'file',
    label: 'Source File',
    category: 'code',
    description: 'Code file, asset, or script in the repository',
    icon: 'FileCode',
    color: '#3f3f46',
    badgeBg: '#f4f4f5',
    borderColor: '#71717a',
  },
  package: {
    type: 'package',
    label: 'Package',
    category: 'code',
    description: 'Package, workspace module, or crate',
    icon: 'Package',
    color: '#27272a',
    badgeBg: '#f4f4f5',
    borderColor: '#52525b',
  },
  library: {
    type: 'library',
    label: 'Library',
    category: 'code',
    description: 'Internal or external utility library',
    icon: 'Library',
    color: '#52525b',
    badgeBg: '#f4f4f5',
    borderColor: '#a1a1aa',
  },
  framework: {
    type: 'framework',
    label: 'Framework',
    category: 'code',
    description: 'Base technology framework or runtime engine',
    icon: 'Braces',
    color: '#09090b',
    badgeBg: '#f4f4f5',
    borderColor: '#27272a',
  },

  // Database & Storage
  database: {
    type: 'database',
    label: 'Database',
    category: 'database',
    description: 'Database instance, warehouse, or cache store',
    icon: 'Database',
    color: '#09090b',
    badgeBg: '#f4f4f5',
    borderColor: '#27272a',
  },
  table: {
    type: 'table',
    label: 'Table / Collection',
    category: 'database',
    description: 'Database entity, schema table, or document collection',
    icon: 'Sheet',
    color: '#27272a',
    badgeBg: '#f4f4f5',
    borderColor: '#52525b',
  },
  field: {
    type: 'field',
    label: 'Field / Column',
    category: 'database',
    description: 'Attribute, column, index, or schema field',
    icon: 'Columns3',
    color: '#52525b',
    badgeBg: '#f4f4f5',
    borderColor: '#a1a1aa',
  },

  // Infrastructure & DevOps
  server: {
    type: 'server',
    label: 'Server / Node',
    category: 'infrastructure',
    description: 'Compute host, VM, container, or serverless pod',
    icon: 'Server',
    color: '#18181b',
    badgeBg: '#f4f4f5',
    borderColor: '#3f3f46',
  },
  environment: {
    type: 'environment',
    label: 'Environment',
    category: 'infrastructure',
    description: 'Deployment tier (Dev, Staging, Production, Edge)',
    icon: 'CloudRain',
    color: '#27272a',
    badgeBg: '#f4f4f5',
    borderColor: '#52525b',
  },
  domain: {
    type: 'domain',
    label: 'Domain / DNS',
    category: 'infrastructure',
    description: 'Domain name, CDN, routing, or SSL endpoint',
    icon: 'Globe',
    color: '#09090b',
    badgeBg: '#f4f4f5',
    borderColor: '#27272a',
  },
  deployment: {
    type: 'deployment',
    label: 'Deployment / Pipeline',
    category: 'infrastructure',
    description: 'CI/CD pipeline, build artifact, or release bundle',
    icon: 'Rocket',
    color: '#18181b',
    badgeBg: '#f4f4f5',
    borderColor: '#3f3f46',
  },

  // AI & Intelligent Systems
  'ai-agent': {
    type: 'ai-agent',
    label: 'AI Agent',
    category: 'ai',
    description: 'Autonomous reasoning agent, orchestrator, or assistant',
    icon: 'Bot',
    color: '#09090b',
    badgeBg: '#f4f4f5',
    borderColor: '#27272a',
  },
  'ai-model': {
    type: 'ai-model',
    label: 'AI Model',
    category: 'ai',
    description: 'Foundation model, fine-tuned LLM, or embedding engine',
    icon: 'Brain',
    color: '#18181b',
    badgeBg: '#f4f4f5',
    borderColor: '#3f3f46',
  },
  'ai-tool': {
    type: 'ai-tool',
    label: 'AI Tool / Skill',
    category: 'ai',
    description: 'Function calling tool, MCP server, or retrieval skill',
    icon: 'Wrench',
    color: '#3f3f46',
    badgeBg: '#f4f4f5',
    borderColor: '#71717a',
  },

  // Management, Tracking & Docs
  task: {
    type: 'task',
    label: 'Task',
    category: 'management',
    description: 'Engineering work item, story, or sub-task',
    icon: 'ListTodo',
    color: '#18181b',
    badgeBg: '#f4f4f5',
    borderColor: '#3f3f46',
  },
  bug: {
    type: 'bug',
    label: 'Bug / Defect',
    category: 'management',
    description: 'Identified issue, regression, or defect',
    icon: 'Bug',
    color: '#09090b',
    badgeBg: '#f4f4f5',
    borderColor: '#27272a',
  },
  test: {
    type: 'test',
    label: 'Test Suite',
    category: 'management',
    description: 'Unit test, integration test, or E2E specification',
    icon: 'CheckCircle2',
    color: '#27272a',
    badgeBg: '#f4f4f5',
    borderColor: '#52525b',
  },
  release: {
    type: 'release',
    label: 'Release / Milestone',
    category: 'management',
    description: 'Versioned release milestone or tag',
    icon: 'Tag',
    color: '#3f3f46',
    badgeBg: '#f4f4f5',
    borderColor: '#71717a',
  },
  document: {
    type: 'document',
    label: 'Document / Spec',
    category: 'management',
    description: 'Architecture RFC, spec document, or design note',
    icon: 'FileText',
    color: '#52525b',
    badgeBg: '#f4f4f5',
    borderColor: '#a1a1aa',
  },
  person: {
    type: 'person',
    label: 'Person / Contributor',
    category: 'organization',
    description: 'Team member, lead, code owner, or contributor',
    icon: 'User',
    color: '#27272a',
    badgeBg: '#f4f4f5',
    borderColor: '#52525b',
  },
  organization: {
    type: 'organization',
    label: 'Organization / Team',
    category: 'organization',
    description: 'Team, squad, company, or open-source collective',
    icon: 'Building2',
    color: '#09090b',
    badgeBg: '#f4f4f5',
    borderColor: '#27272a',
  },
  custom: {
    type: 'custom',
    label: 'Custom Node',
    category: 'custom',
    description: 'User-defined custom architecture primitive',
    icon: 'Boxes',
    color: '#3f3f46',
    badgeBg: '#f4f4f5',
    borderColor: '#71717a',
  },
};

export const CATEGORY_LABELS: Record<string, string> = {
  product: 'Product & Planning',
  architecture: 'Architecture & Backend',
  code: 'Code & Implementation',
  infrastructure: 'Infrastructure & Cloud',
  database: 'Data & Storage',
  ai: 'AI & Machine Learning',
  management: 'Management & Quality',
  organization: 'Team & Organization',
  custom: 'Custom Extensions',
};
