import type { UPGView } from '../types/graph';

export const DEFAULT_VIEWS: Omit<UPGView, 'projectId'>[] = [
  {
    id: 'view-all',
    name: 'Unified Graph',
    perspective: 'all',
    description: 'Complete unrestricted representation of all nodes and relationships',
    icon: 'Network',
  },
  {
    id: 'view-architecture',
    name: 'Architecture View',
    perspective: 'architecture',
    description: 'System topology, services, modules, APIs, and inter-service communications',
    icon: 'Layers',
    filterCategories: ['architecture', 'infrastructure', 'database', 'code'],
    filterNodeTypes: ['module', 'service', 'api', 'endpoint', 'database', 'event', 'integration'],
  },
  {
    id: 'view-dependency',
    name: 'Dependency View',
    perspective: 'dependency',
    description: 'Explicit dependency chains, blocking tasks, package trees, and imports',
    icon: 'GitFork',
    filterRelationshipTypes: ['depends-on', 'blocks', 'imports', 'uses', 'extends', 'inherits'],
  },
  {
    id: 'view-product',
    name: 'Product & Planning View',
    perspective: 'product',
    description: 'Vision, problems, features, requirements, user journeys, and roadmap milestones',
    icon: 'Compass',
    filterCategories: ['product', 'management'],
    filterNodeTypes: ['project', 'product', 'feature', 'requirement', 'release', 'page'],
  },
  {
    id: 'view-ui',
    name: 'UI & Frontend View',
    perspective: 'ui',
    description: 'Page hierarchy, visual components, design tokens, and UI element trees',
    icon: 'Layout',
    filterCategories: ['product', 'code'],
    filterNodeTypes: ['page', 'component', 'ui-element'],
  },
  {
    id: 'view-infrastructure',
    name: 'Infrastructure & Cloud View',
    perspective: 'infrastructure',
    description: 'Domains, CDN edge nodes, host servers, containers, VPCs, and deployments',
    icon: 'Cloud',
    filterCategories: ['infrastructure', 'database'],
    filterNodeTypes: ['domain', 'server', 'environment', 'deployment', 'database'],
  },
  {
    id: 'view-security',
    name: 'Security & Auth View',
    perspective: 'security',
    description: 'Authentication boundaries, authorization rules, access control, and audited tokens',
    icon: 'ShieldCheck',
    filterRelationshipTypes: ['authenticates', 'stores', 'reads', 'writes'],
    filterNodeTypes: ['service', 'endpoint', 'database', 'table', 'person', 'organization', 'api'],
  },
  {
    id: 'view-development',
    name: 'Development & QA View',
    perspective: 'development',
    description: 'Epics, active tasks, bug reports, test suites, and pull-request release tags',
    icon: 'CheckCircle',
    filterCategories: ['management', 'code'],
    filterNodeTypes: ['task', 'bug', 'test', 'release', 'function', 'file', 'package'],
  },
  {
    id: 'view-ai',
    name: 'AI & Agentic Systems View',
    perspective: 'ai',
    description: 'Agents, foundation models, fine-tunes, tool integrations, and vector stores',
    icon: 'Bot',
    filterCategories: ['ai', 'architecture', 'database'],
    filterNodeTypes: ['ai-agent', 'ai-model', 'ai-tool', 'service', 'database', 'api'],
  },
  {
    id: 'view-database',
    name: 'Database & Schema View',
    perspective: 'database',
    description: 'Databases, relational tables, collections, columns, fields, and foreign keys',
    icon: 'Database',
    filterCategories: ['database'],
    filterNodeTypes: ['database', 'table', 'field'],
  },
];
