import type { RelationshipTypeDefinition } from '@hupa/core';

export const BUILTIN_RELATIONSHIP_TYPES: Record<string, RelationshipTypeDefinition> = {
  contains: {
    type: 'contains',
    label: 'contains',
    description: 'Parent entity encapsulates child component or subsystem',
    color: '#09090b',
    lineStyle: 'solid',
  },
  'depends-on': {
    type: 'depends-on',
    label: 'depends on',
    description: 'Direct structural or runtime dependency required for operation',
    color: '#18181b',
    lineStyle: 'solid',
  },
  uses: {
    type: 'uses',
    label: 'uses',
    description: 'Consumes functionality or interface of target entity',
    color: '#27272a',
    lineStyle: 'solid',
  },
  calls: {
    type: 'calls',
    label: 'calls',
    description: 'Direct function invocation, RPC, or API endpoint execution',
    color: '#3f3f46',
    lineStyle: 'dashed',
  },
  imports: {
    type: 'imports',
    label: 'imports',
    description: 'Source code module or package import',
    color: '#52525b',
    lineStyle: 'dotted',
  },
  extends: {
    type: 'extends',
    label: 'extends',
    description: 'Inherits and expands base class, schema, or framework capability',
    color: '#18181b',
    lineStyle: 'solid',
  },
  implements: {
    type: 'implements',
    label: 'implements',
    description: 'Realizes an abstract interface, contract, or specification',
    color: '#27272a',
    lineStyle: 'dashed',
  },
  stores: {
    type: 'stores',
    label: 'stores',
    description: 'Persists state or records into database, table, or cache',
    color: '#09090b',
    lineStyle: 'solid',
  },
  reads: {
    type: 'reads',
    label: 'reads',
    description: 'Queries or retrieves data from target store or stream',
    color: '#3f3f46',
    lineStyle: 'dashed',
  },
  writes: {
    type: 'writes',
    label: 'writes',
    description: 'Mutates or writes records to target database or file',
    color: '#18181b',
    lineStyle: 'solid',
  },
  authenticates: {
    type: 'authenticates',
    label: 'authenticates',
    description: 'Validates identity, token, session, or signature',
    color: '#09090b',
    lineStyle: 'solid',
  },
  'deploys-to': {
    type: 'deploys-to',
    label: 'deploys to',
    description: 'Publishes or provisions artifact to target environment or host',
    color: '#27272a',
    lineStyle: 'dashed',
    animated: true,
  },
  triggers: {
    type: 'triggers',
    label: 'triggers',
    description: 'Emits an event or initiates automated workflow execution',
    color: '#18181b',
    lineStyle: 'dashed',
    animated: true,
  },
  produces: {
    type: 'produces',
    label: 'produces',
    description: 'Outputs data, artifact, message, or stream',
    color: '#27272a',
    lineStyle: 'solid',
  },
  consumes: {
    type: 'consumes',
    label: 'consumes',
    description: 'Listens to event queue or ingests input payload',
    color: '#3f3f46',
    lineStyle: 'dashed',
  },
  'belongs-to': {
    type: 'belongs-to',
    label: 'belongs to',
    description: 'Membership relationship with group, project, or domain',
    color: '#71717a',
    lineStyle: 'dotted',
  },
  replaces: {
    type: 'replaces',
    label: 'replaces',
    description: 'Supersedes legacy component or deprecated API',
    color: '#18181b',
    lineStyle: 'dashed',
  },
  blocks: {
    type: 'blocks',
    label: 'blocks',
    description: 'Impediment blocking progression of dependent task/feature',
    color: '#09090b',
    lineStyle: 'solid',
  },
  'related-to': {
    type: 'related-to',
    label: 'related to',
    description: 'Associative link or context relevance',
    color: '#a1a1aa',
    lineStyle: 'dotted',
  },
  'connects-to': {
    type: 'connects-to',
    label: 'connects to',
    description: 'Network socket, tunnel, or direct bridge',
    color: '#18181b',
    lineStyle: 'solid',
  },
  references: {
    type: 'references',
    label: 'references',
    description: 'Cites RFC document, external guideline, or schema spec',
    color: '#71717a',
    lineStyle: 'dotted',
  },
  inherits: {
    type: 'inherits',
    label: 'inherits',
    description: 'Inherits configuration, security context, or attributes',
    color: '#27272a',
    lineStyle: 'solid',
  },
  'communicates-with': {
    type: 'communicates-with',
    label: 'communicates with',
    description: 'Bidirectional sync or communication protocol',
    color: '#18181b',
    lineStyle: 'dashed',
    bidirectional: true,
  },
  custom: {
    type: 'custom',
    label: 'custom relationship',
    description: 'User-defined semantic relationship',
    color: '#52525b',
    lineStyle: 'solid',
  },
};
